---
name: Module-Used
version: v1.1.0
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Find modules loaded by Perl code without running it.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  English: 0
  Exporter: 5.57
  File::Next: 1.02
  PPI::Document: 1.203
  Readonly: 1.03
  strict: 0
  utf8: 0
  version: 0.74
  warnings: 0
build_requires:
  Test::Deep: 0.098
  Test::More: 0.72
dynamic_config: 0
provides:
  Module::Used:
    file: lib/Module/Used.pm
    version: v1.1.0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
configure_requires:
  Module::Build: 0.2808
