---
name: Module-Used
version: v1.002000
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Find modules loaded by Perl code without running it.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  English: 0
  Exporter: 5.57
  File::Next: 1.02
  PPI::Document: 1.203
  Readonly: 1.03
  strict: 0
  utf8: 0
  version: 0.74
  warnings: 0
build_requires:
  Test::Deep: 0.098
  Test::More: 0.72
dynamic_config: 0
provides:
  Module::Used:
    file: lib/Module/Used.pm
    version: v1.002000
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - xt
  file: []
configure_requires:
  Module::Build: 0.2808
